# Generated by using Rcpp::compileAttributes() -> do not edit by hand
sacat_gh_log_weights_cpp <- function(node, order) {
    .Call(`_SACAT_sacat_gh_log_weights_cpp`, node, order)
}

sacat_count_log_hy_adaptive_cpp <- function(y, N, eta, sigma, node, log_raw_weight, iterations = 80L, score_tolerance = 1e-12, bracket_tolerance = 1e-12) {
    .Call(`_SACAT_sacat_count_log_hy_adaptive_cpp`, y, N, eta, sigma, node, log_raw_weight, iterations, score_tolerance, bracket_tolerance)
}

sacat_count_moments_adaptive_cpp <- function(y, N, eta, sigma, node, log_raw_weight, need_moments = TRUE, iterations = 80L, score_tolerance = 1e-12, bracket_tolerance = 1e-12) {
    .Call(`_SACAT_sacat_count_moments_adaptive_cpp`, y, N, eta, sigma, node, log_raw_weight, need_moments, iterations, score_tolerance, bracket_tolerance)
}

sacat_mean_log_relative_cpp <- function(location, sigma, z, weight) {
    .Call(`_SACAT_sacat_mean_log_relative_cpp`, location, sigma, z, weight)
}
